### ISSUE TITLE
multi_node_snapshot does not work

### ISSUE THREAD

**Issue by msakai** [chainer/chainer-pytorch-migration#11]
I tried to port ChainerMN training script using `chainer_pytorch_migration.chainermn` and noticed that `multi_node_snapshot` did not work.

I guess `multi_node_snapshot` is not supported, but I report it here just for record.

Script:
https://gist.github.com/msakai/06cf2f4ad937ba3215daee227695499e

Result:

```
$ mpiexec -n 1 -- python train_mnist_chainermn_pytorch.py
Warning: using naive communicator because only naive supports CPU-only execution
==========================================
Num process (COMM_WORLD): 1
Using pure_nccl communicator
Num unit: 1000
Num Minibatch-size: 100
Num epoch: 20
==========================================
     total [..................................................]  0.83%
this epoch [########..........................................] 16.67%
       100 iter, 0 epoch / 20 epochs
       inf iters/sec. Estimated time to finish: 0:00:00.
     total [..................................................]  1.67%
this epoch [################..................................] 33.33%
       200 iter, 0 epoch / 20 epochs
      30.4 iters/sec. Estimated time to finish: 0:06:28.157568.
     total [#.................................................]  2.50%
this epoch [#########################.........................] 50.00%
       300 iter, 0 epoch / 20 epochs
    30.044 iters/sec. Estimated time to finish: 0:06:29.433081.
     total [#.................................................]  3.33%
this epoch [#################################.................] 66.67%
       400 iter, 0 epoch / 20 epochs
    30.166 iters/sec. Estimated time to finish: 0:06:24.539380.
     total [##................................................]  4.17%
this epoch [#########################################.........] 83.33%
       500 iter, 0 epoch / 20 epochs
    30.292 iters/sec. Estimated time to finish: 0:06:19.632452.
Traceback (most recent call last):
  File "train_mnist_chainermn_pytorch.py", line 150, in <module>
    main()
  File "train_mnist_chainermn_pytorch.py", line 146, in main
    trainer.run(train_loader, max_epochs=args.epoch)
  File "/Users/sakai/src/chainer-pytorch-migration/chainer_pytorch_migration/ignite/extensions.py", line 293, in pre_run
    Engine.run(self.engine, data, max_epochs)
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ignite/engine/engine.py", line 446, in run
    self._handle_exception(e)
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ignite/engine/engine.py", line 410, in _handle_exception
    raise e
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ignite/engine/engine.py", line 433, in run
    hours, mins, secs = self._run_once_on_dataset()
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ignite/engine/engine.py", line 399, in _run_once_on_dataset
    self._handle_exception(e)
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ignite/engine/engine.py", line 410, in _handle_exception
    raise e
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ignite/engine/engine.py", line 392, in _run_once_on_dataset
    self._fire_event(Events.ITERATION_COMPLETED)
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ignite/engine/engine.py", line 345, in _fire_event
    func(self, *(event_args + args), **kwargs)
  File "/Users/sakai/src/chainer-pytorch-migration/chainer_pytorch_migration/ignite/extensions.py", line 246, in run_extensions_on_iter
    self.run_extensions()
  File "/Users/sakai/src/chainer-pytorch-migration/chainer_pytorch_migration/ignite/extensions.py", line 280, in run_extensions
    entry.extension(self)
  File "/Users/sakai/src/chainer/chainermn/extensions/_multi_node_snapshot.py", line 208, in __call__
    self.snapshot(trainer)
  File "/Users/sakai/src/chainer/chainer/training/extensions/_snapshot.py", line 407, in __call__
    self._make_snapshot(trainer)
  File "/Users/sakai/src/chainer/chainer/training/extensions/_snapshot.py", line 411, in _make_snapshot
    serialized_target = npz.serialize(target)
  File "/Users/sakai/src/chainer/chainer/serializers/npz.py", line 80, in serialize
    s.save(obj)
  File "/Users/sakai/src/chainer/chainer/serializer.py", line 67, in save
    obj.serialize(self)
  File "/Users/sakai/src/chainer-pytorch-migration/chainer_pytorch_migration/ignite/extensions.py", line 300, in serialize
    '_Snapshot').filename
  File "/Users/sakai/src/chainer/chainer/training/trainer.py", line 291, in get_extension
    raise ValueError('extension %s not found' % name)
ValueError: extension _Snapshot not found
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[58846,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by emcastillo** [comment]
#14 should fix it. Thanks!
